---

- name: config
  hosts: routers
  connection: network_cli
  gather_facts: no 
  tasks:
     - name: configure provider1
       set_fact:
         provider:
           username: admin
           password: admin 

      - name: set hostname
        ios_config:
          provider:  "{{ R1 }}"
          lines: hostname {{ inventory_hostname}}

      - name: Interface IP 
        ios_config:
           provider: "{{ R1 }}"
           lines: 
<<<<<<< HEAD
           - ip add 192.168.78.1 255.255.255.255.0
=======
           - ip add 192.168.28.1 255.255.255.255.0
>>>>>>> 2375d09 (Provider2)
           - no shu 
           - full-duple
           parents: e1/0

      - name: Interface IP 
        ios_config:
           provider: "{{ R1 }}"
           lines: 
<<<<<<< HEAD
           - ip add 10.10.78.1 255.255.255.255.0
=======
           - ip add 10.10.28.1 255.255.255.255.0
>>>>>>> 2375d09 (Provider2)
           - no shu 
           - full-duple
           parents: s2/0
    

