---

- name: mpls ansible project

- hosts: routers

  gather_facts: false

  connection: network_cli



  tasks:

#    - name: change Hostname omoyele

 #     ios_config: 

 #       lines: 

  #        - hostname R1



    - name: Run ospf

      ios_config:

        lines:

         - network 0.0.0.0 255.255.255.255 area 0

        parents: router ospf 200

- hosts: R1

  gather_facts: false

  connection: network_cli



  tasks:

    - name: configure int e1/0 interface

      ios_config:

        lines:  
        
           - descri harsh

           - ip add 192.168.200.1 255.255.255.0

           - no shutdown

        parents: int e1/0

    - name: configure loopback interface for R1

      ios_config:

        lines:

           - ip add 1.1.1.1 255.255.255.240

           - no shutdown

        parents: int loopback 0


- hosts: R2

  gather_facts: false

  connection: network_cli



  tasks:

    - name: configure int e1/0 interface

      ios_config:

        lines:

           - ip add 192.168.10.1 255.255.255.0

           - no shutdown

        parents: int e1/0

    - name: configure int s2/0 interface

      ios_config:

        lines:

           - ip add 21.20.20.210 255.255.255.0

           - no shutdown

        parents: int s2/0



    - name: configure loopback

      ios_config:

        lines:

           - ip add 2.2.2.2 255.255.255.0
        parents: int loopback 0






- hosts: R3

  gather_facts: false

  connection: network_cli



  tasks:

    - name: configure int e1/0 interface

      ios_config:

        lines:

           - ip add 192.168.100.1 255.255.255.0

           - no shutdown

        parents: int e1/0

    - name: configure int s2/0 interface

      ios_config:

        lines:

           - ip add 172.27.111.250 255.255.255.0

           - no shutdown

        parents: int s2/0


    - name: configure loopback for r3

      ios_config:

        lines:

           - ip add 33.33.33.33 255.255.255.255
           - description EngrAmin
           - no shutdown

        parents: int loopback 20
